name       : haskell-tar
version    : 0.5.1.0
release    : 5
source     :
    - https://hackage.haskell.org/package/tar-0.5.1.0/tar-0.5.1.0.tar.gz : c89d697b6472b739db50e61201251fcaf8a8f5b595b1d9a488d395d7d5ce4b68
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library is for working with ".tar" archive files.
description: |
    This library is for working with ".tar" archive files.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
