name       : haskell-tar
version    : 0.5.0.3
release    : 3
source     :
    - http://hackage.haskell.org/package/tar-0.5.0.3/tar-0.5.0.3.tar.gz : d8d9ad876365f88bdccd02073049e58715cd5ba94de06eb98e21d595244918a3
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library is for working with ".tar" archive files.
description: |
    This library is for working with ".tar" archive files.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
