name       : haskell-tar
version    : 0.5.1.1
release    : 7
source     :
    # Revision 6
    - https://hackage.haskell.org/package/tar-0.5.1.1/tar-0.5.1.1.tar.gz : b384449f62b2b0aa3e6d2cb1004b8060b01f21ec93e7b63e7af6d8fad8a9f1de
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library is for working with ".tar" archive files.
description: |
    This library is for working with ".tar" archive files.
builddeps  :
    - ghc-devel
setup      : |
    cp $pkgfiles/6.cabal tar.cabal
    %haskell_configure -f -old-time -f -old-bytestring
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
