name       : haskell-tar
version    : 0.5.0.3
release    : 1
source     :
    - http://hackage.haskell.org/package/tar-0.5.0.3/tar-0.5.0.3.tar.gz : d8d9ad876365f88bdccd02073049e58715cd5ba94de06eb98e21d595244918a3
license    : BSD-3-Clause
component  : programming
summary    : This library is for working with ".tar" archive files.
description: |
    This library is for working with ".tar" archive files.
builddeps  :
    - ghc
setup      : |
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 tar-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/tar-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/tar-$version/*.a
